### ISSUE TITLE
Nobara Linux

### ISSUE THREAD

**Issue by shimniok** [RockyC36/StickerPack#1]
I sure would love to see a sticker for my favorite distro, Nobara, popular among Linux gamers. See: https://nobaraproject.org/

**Comment by RockyC36** [comment]
I would LOVE to do a Nobara sticker, but I can’t find any artwork online. I guess I’m going to have to install Nobara in a VM and look for an icon.

**Comment by shimniok** [comment]
Sweet! I bet you could reach out to the main dev, @GloriousEggroll on
Twitter (err... X). Hopefully he has vector or hi res logos.

**Comment by ludwig234** [comment]
I used a live ISO and i found this icon from /usr/share/icons/hicolor/scalable/apps/start-here.svg
It should be sufficient.
![Nobara logo](https://github.com/RockyC36/StickerPack/assets/25568152/06f7cf0e-ead7-43a8-8642-54e379293acb)
