### ISSUE TITLE
Icons doesn't look as intended

### ISSUE THREAD

**Issue by Darkpepito** [RockyC36/StickerPack#3]
I don't know why but all icons are looking like this :

![Image collée](https://github.com/RockyC36/StickerPack/assets/98229948/93c3fb33-8fda-4456-a039-839a68cddc40)

Is it me or something is off ?

**Comment by RockyC36** [comment]
It looks like whatever app you're using to open the SVG file is having issues. I noticed a similar issue when I opened the file in Affinity. 

Unfortunately, I don't know how to fix, as I'm not a graphic designer, just a hobbyist. My only recommendation is to try with a different application.

**Comment by ludwig234** [comment]
The problem was that Affinity didn't like the corner tool thing.
I fixed it by converting the stroke to paths.
I will also update all the PNGs I made so they don't have that error.
